#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Next.js loads this file; .gitignore already ignores `.env*` except `.env.example`.
# Production secrets go to Vercel, not GitHub — this repo has no Actions workflows.
ENV_FILE=".env.local"

supabase_project_ref() {
  local url="${1%/}"
  url="${url#https://}"
  url="${url#http://}"
  printf '%s' "${url%%.supabase.co*}"
}

require_secrets_untracked() {
  local tracked staged
  if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    warn "not inside a git work tree — cannot verify that secrets stay untracked"
    return 0
  fi
  if ! git check-ignore -q "$ENV_FILE"; then
    warn "$ENV_FILE is not gitignored. Refusing to write secrets that git could commit."
    exit 1
  fi
  tracked=$(git ls-files --cached -- '.env' '.env.*' '*.env' | grep -vE '(^|/)\.env\.example$' || true)
  if [[ -n "$tracked" ]]; then
    warn "these env files are tracked in git. Untrack them before continuing:"
    printf '%s\n' "$tracked" | while IFS= read -r f; do note "  $f"; done
    exit 1
  fi
  staged=$(git diff --cached --name-only | grep -E '(^|/)\.env(\.|$)' | grep -vE '(^|/)\.env\.example$' || true)
  if [[ -n "$staged" ]]; then
    warn "these env files are staged. Unstage them before continuing:"
    printf '%s\n' "$staged" | while IFS= read -r f; do note "  $f"; done
    exit 1
  fi
  note "$ENV_FILE is gitignored. Placeholder-only .env.example may stay tracked."
}

write_local_env() {
  local key="$1" value="$2"
  if [[ -z "$value" ]]; then
    warn "skipped $key — empty value; re-run this wizard when you have it"
    return 0
  fi
  write_env "$key" "$value"
  chmod 600 "$ENV_FILE" 2>/dev/null || true
}

TOTAL_STAGES=9

banner "Verse Clash — prepare production"

# ── 1. Secret hygiene ─────────────────────────────────────────────────────
stage "Keep secrets out of git"
say "Secrets stay in gitignored $ENV_FILE and in Vercel Environment Variables."
say "This repo has no GitHub Actions workflows, so nothing is written to gh secret."
note "The only env file git may track is .env.example (placeholders, no secrets)."
require_secrets_untracked
pause "Continue?"

# ── 2. Supabase project ───────────────────────────────────────────────────
stage "Create the Supabase project"
say "Hosted rooms need a Supabase project. Skip creation if you already have one."
open_url "https://supabase.com/dashboard/new"
step "Sign in, then New project. Name it verse-clash (or similar)."
step "Pick an org and a region close to you. Set a database password and store it in your password manager — this wizard does not save it."
step "Wait until the project is ready, then open Project Settings → General (or the Connect dialog) and copy the Project URL."
note "It looks like https://<project-ref>.supabase.co"
ask NEXT_PUBLIC_SUPABASE_URL "Paste the Project URL:"
write_local_env NEXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL"

# ── 3. API keys ───────────────────────────────────────────────────────────
stage "Copy Supabase API keys"
say "This app still reads NEXT_PUBLIC_SUPABASE_ANON_KEY and SUPABASE_SERVICE_ROLE_KEY."
say "Paste the publishable/anon key into the first, and the secret/service_role key into the second."
if [[ -n "${NEXT_PUBLIC_SUPABASE_URL:-}" ]]; then
  open_url "https://supabase.com/dashboard/project/$(supabase_project_ref "$NEXT_PUBLIC_SUPABASE_URL")/settings/api-keys"
else
  open_url "https://supabase.com/dashboard"
  step "Open your project → Project Settings → API Keys."
fi
step "Prefer the API Keys tab: copy the Publishable key (sb_publishable_…). If you only have Legacy API Keys, copy the anon key instead."
ask_secret NEXT_PUBLIC_SUPABASE_ANON_KEY "Paste the publishable or anon key:"
step "Copy a Secret key (sb_secret_…). Reveal it if needed. If you only have Legacy API Keys, copy the service_role key instead."
note "Never put this secret in the repo, a commit, or client-side code."
ask_secret SUPABASE_SERVICE_ROLE_KEY "Paste the secret or service_role key:"
write_local_env NEXT_PUBLIC_SUPABASE_ANON_KEY "$NEXT_PUBLIC_SUPABASE_ANON_KEY"
write_local_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"
require_secrets_untracked

# ── 4. Anthropic API key ──────────────────────────────────────────────────
stage "Anthropic API key for round composition"
say "Rounds ask Claude to assemble each team's submitted words into a verse and judge them."
say "Without this key, rounds fall back to deterministic template-filling — the game still works, just less lively."
open_url "https://console.anthropic.com/settings/keys"
step "Create a key (or reuse one) and copy it."
note "Never put this secret in the repo, a commit, or client-side code."
ask_secret ANTHROPIC_API_KEY "Paste the Anthropic API key (Enter to skip):"
if [[ -n "${ANTHROPIC_API_KEY:-}" ]]; then
  write_local_env ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"
else
  SKIPPED+=("Add ANTHROPIC_API_KEY — rounds will use the deterministic fallback composer")
fi
require_secrets_untracked

# ── 5. Anonymous auth ─────────────────────────────────────────────────────
stage "Enable Anonymous sign-ins"
say "Players join with a room code and display name — no email accounts."
if [[ -n "${NEXT_PUBLIC_SUPABASE_URL:-}" ]]; then
  open_url "https://supabase.com/dashboard/project/$(supabase_project_ref "$NEXT_PUBLIC_SUPABASE_URL")/auth/providers"
else
  open_url "https://supabase.com/dashboard"
  step "Open your project → Authentication → Sign In / Providers."
fi
step "Find Allow anonymous sign-ins and turn it on. Save if the page asks."
note "CAPTCHA is optional later if anonymous sign-ups get abused."
pause "Anonymous sign-ins enabled?"

# ── 6. Schema migration ───────────────────────────────────────────────────
stage "Apply the game schema"
say "Run the in-repo migration so rooms, RLS, and Realtime publication exist."
if [[ -n "${NEXT_PUBLIC_SUPABASE_URL:-}" ]]; then
  open_url "https://supabase.com/dashboard/project/$(supabase_project_ref "$NEXT_PUBLIC_SUPABASE_URL")/sql/new"
else
  open_url "https://supabase.com/dashboard"
  step "Open your project → SQL Editor → New query."
fi
step "Open supabase/migrations/20260818120000_game_schema.sql in your editor."
step "Paste the full file into the SQL Editor and run it."
step "Confirm tables such as rooms, players, teams, and rounds appear with no error."
if ! confirm "Did the migration run without errors?"; then
  SKIPPED+=("Apply supabase/migrations/20260818120000_game_schema.sql in the SQL Editor")
  warn "schema not applied — hosted rooms will not work until it is"
fi

# ── 7. Vercel project ─────────────────────────────────────────────────────
stage "Import the repo on Vercel"
say "Next.js production for this app is Vercel. Import the GitHub repo; do not paste secrets into the repo."
open_url "https://vercel.com/new"
step "Import the GitHub repository alassiter/verse-clash."
step "Framework Preset should be Next.js. Leave Root Directory as ."
step "Skip environment variables on this import screen — the next stage adds them."
step "Create the project. The first deploy may boot without Supabase keys; that is expected."
ask VERCEL_PROJECT_URL "Paste the Vercel project URL (https://vercel.com/…/…):"
note "Used only to open the next page. Not written to $ENV_FILE."

# ── 8. Vercel env vars ────────────────────────────────────────────────────
stage "Put secrets on Vercel, not in git"
say "Vercel encrypts env vars. Mark the service-role and Anthropic keys Sensitive so the dashboard cannot show them later."
say "Preview deploys will share this same Supabase project."
if [[ -n "${VERCEL_PROJECT_URL:-}" ]]; then
  open_url "${VERCEL_PROJECT_URL%/}/settings/environment-variables"
else
  open_url "https://vercel.com/dashboard"
  step "Open this project → Settings → Environment Variables."
fi
step "Add NEXT_PUBLIC_SUPABASE_URL — the Project URL from earlier. Environments: Production and Preview."
step "Add NEXT_PUBLIC_SUPABASE_ANON_KEY — the publishable/anon key. Production and Preview."
step "Add SUPABASE_SERVICE_ROLE_KEY — the secret/service_role key. Production and Preview. Turn on Sensitive."
if [[ -n "${ANTHROPIC_API_KEY:-}" ]]; then
  step "Add ANTHROPIC_API_KEY — the key from the Anthropic step. Production and Preview. Turn on Sensitive."
fi
step "Do not upload .env.local, do not commit it, and do not add these to GitHub Actions secrets."
if ! confirm "Are the Supabase variables (and ANTHROPIC_API_KEY, if you set one) saved on Vercel?"; then
  SKIPPED+=("Add NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_ANON_KEY, SUPABASE_SERVICE_ROLE_KEY, ANTHROPIC_API_KEY on Vercel (Sensitive for the service-role and Anthropic keys)")
  warn "Vercel env vars not confirmed — production will not see Supabase or Claude"
fi
require_secrets_untracked

# ── 9. Production deploy ──────────────────────────────────────────────────
stage "Redeploy production"
say "Env var changes apply only to the next deployment."
if confirm "Redeploy production now?"; then
  if [[ -n "${VERCEL_PROJECT_URL:-}" ]]; then
    open_url "${VERCEL_PROJECT_URL%/}/deployments"
  else
    open_url "https://vercel.com/dashboard"
    step "Open this project → Deployments."
  fi
  step "On the latest deployment, Redeploy. Clear Use existing Build Cache if you see that checkbox."
  pause "Redeploy started?"
else
  SKIPPED+=("Redeploy on Vercel after env vars are saved")
fi
ask PRODUCTION_URL "Paste the production URL (https://….vercel.app), or Enter to skip:"
if [[ -n "${PRODUCTION_URL:-}" ]]; then
  note "production: $PRODUCTION_URL"
fi
require_secrets_untracked

# ──────────────────────────────────────────────────────────────────────────

finish
note "Local secrets: $ENV_FILE (gitignored). Production secrets: Vercel Environment Variables."
note "Never commit $ENV_FILE, .env, or .env.production."
